[2024-11-30T01:48:47.902+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1.load_model_task manual__2024-11-30T01:43:54+00:00 [queued]>
[2024-11-30T01:48:47.912+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1.load_model_task manual__2024-11-30T01:43:54+00:00 [queued]>
[2024-11-30T01:48:47.913+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-30T01:48:47.913+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-30T01:48:47.914+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-30T01:48:47.932+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_model_task> on 2024-11-30 01:43:54+00:00
[2024-11-30T01:48:47.941+0000] {standard_task_runner.py:55} INFO - Started process 904 to run task
[2024-11-30T01:48:47.944+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_model_task', 'manual__2024-11-30T01:43:54+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/***_test.py', '--cfg-path', '/tmp/tmpzvujdnbo']
[2024-11-30T01:48:47.946+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask load_model_task
[2024-11-30T01:48:48.000+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow_Lab1.load_model_task manual__2024-11-30T01:43:54+00:00 [running]> on host 0ad9afc8453f
[2024-11-30T01:48:48.064+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=stephy
AIRFLOW_CTX_DAG_ID=Airflow_Lab1
AIRFLOW_CTX_TASK_ID=load_model_task
AIRFLOW_CTX_EXECUTION_DATE=2024-11-30T01:43:54+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-30T01:43:54+00:00
[2024-11-30T01:48:48.082+0000] {logging_mixin.py:137} INFO - Optimal no. of clusters: 8
[2024-11-30T01:48:48.083+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but KMeans was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

[2024-11-30T01:48:48.165+0000] {python.py:177} INFO - Done. Returned value was: 9
[2024-11-30T01:48:48.204+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=Airflow_Lab1, task_id=load_model_task, execution_date=20241130T014354, start_date=20241130T014847, end_date=20241130T014848
[2024-11-30T01:48:48.237+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-11-30T01:48:48.255+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
